-
  name: 'Homepage'
  uriPattern: ''
  defaults:
    '@package': 'project.emulate'
    '@controller': 'standard'
    '@action': 'index'

-
  name: 'Homepage'
  uriPattern: '({@action})'
  defaults:
    '@package': 'project.emulate'
    '@controller': 'standard'
    '@action': 'index'

-
  name: 'Homepage'
  uriPattern: '{@controller}(/{@action})'
  defaults:
    '@package': 'project.emulate'
    '@controller': 'standard'
    '@action': 'index'

-
  name: 'Homepage'
  uriPattern: 'emulate/{emulator}/{controller}/{action}}'
  defaults:
    '@package': 'project.emulate'
    '@controller': 'standard'
    '@action': 'emulatorController'
  httpMethods: ['POST']
