-
  name: 'Homepage'
  uriPattern: ''
  defaults:
    '@package': 'project.emulate'
    '@controller': 'standard'
    '@action': 'index'

-
  name: 'Homepage'
  uriPattern: '({@action})'
  defaults:
    '@package': 'project.emulate'
    '@controller': 'standard'
    '@action': 'index'

-
  name: 'Homepage'
  uriPattern: '{@controller}(/{@action})'
  defaults:
    '@package': 'project.emulate'
    '@controller': 'standard'
    '@action': 'index'

-
  name: 'Homepage'
  uriPattern: '{emulator}/{controller}/{action}}'
  defaults:
    '@package': 'project.emulate'
    '@controller': 'standard'
    '@action': 'emulatorController'
