-
  name: 'Homepage'
  uriPattern: ''
  defaults:
    '@package': 'project.emulate'
    '@controller': 'Standard'
    '@action': 'index'

-
  name: 'Homepage'
  uriPattern: '({@action})'
  defaults:
    '@package': 'project.emulate'
    '@controller': 'Standard'
    '@action': 'index'

-
  name: 'Homepage'
  uriPattern: '{controller}(/{action})'
  defaults:
    '@package': 'project.emulate'
    '@controller': 'Standard'
    '@action': 'index'
