TYPO3:
  Flow:
    security:
      enable: TRUE
      authentication:
        providers:
          DefaultProvider:
            provider: PersistedUsernamePasswordProvider
project:
  emulate:
    emulators: ['emulate8086', 'emulate8085']